### ISSUE TITLE
Create, view , update and delete profile

### ISSUE THREAD

**Issue by claudio-cruz** [claudio-cruz/taskify_app#2]
**As a** user, **I want** to be able to view, create, update, or delete my profile, **so that** I can personalize my account .

### Acceptance criteria:
- Users are able to view their profile information.
- Users can update their profile information as needed.
- Users can delete their profile and all data attached to it if they choose to do so.

### Tasks:
- [x]  Design a user profile page with editable fields.
- [x]  Create functionality to allow users to edit and delete their profile.
- [ ]  Ensure that user profile information is securely stored and displayed.
