### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by claudio-cruz** [claudio-cruz/taskify_app#3]
**As a** user, **I want** a navbar that allows me to easily navigate the platform, **so that** I can quickly access different features and sections of the platform.

### Acceptance criteria:
- The navbar is prominently displayed on all the platform pages.
- The navbar is intuitive and easy to use.
- The navbar provides access to all major sections of the platform.
- The navbar is customized for users that are authenticated and for users that aren't authenticated.

### Tasks:
- [x] Design a navbar with links to major sections of the platform.
- [x]  Ensure that the navbar is accessible and functional on all devices.
- [x]  Customize the navbar for users that are authenticated and for users that aren't authenticated.
