### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by claudio-cruz** [claudio-cruz/taskify_app#7]
**As a** logged-in user, **I want** to be able to see, create, edit, or delete notes, **so that** I can easily jot down and save important information.

### Acceptance criteria:
- Users are able to view all their notes.
- Users can create new notes.
- Users can edit and delete existing notes.

### Tasks:
- [x] Create a form to add new notes.
- [x]  Implement functionality to create, edit, and delete notes.
- [x]  Ensure that note data is securely stored and displayed.
